export const CHANGE_PAGE_TITLE = 'CHANGE_PAGE_TITLE'
export const DATA_FETCHING = 'DATA_FETCHING'
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS'
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR'
